#!/usr/bin/env python3

# Creates a dockerized stage3.
import os, sys, re, docker
from include.gentoomuch_common import read_file_lines, write_file_lines
from include.portage_directory_combiner import portage_directory_combiner


