#!/usr/bin/env python3

import sys, os
from include.gentoomuch_common import read_file_lines, write_file_lines

custom_http = False
custom_key = False
only_arch = False
if len(sys.argv) > 1:
    arch = sys.argv[1].strip()
    if len(sys.argv) == 2:
        only_arch = True
if len(sys.argv) > 2:
    arch = sys.argv[1].strip()
    tag = sys.argv[2].strip()
if len(sys.argv) > 3:
    custom_http = True
    http = sys.argv[3].strip()
if len(sys.argv) < 1 or len(sys.argv) > 4:
    sys.exit('Usage: pull-stage3 <arch> [tag] [http-server]\n\tUpstream support:\n\t\tarchitectures: amd64|arm64|armv5tel|armv6j_hardfp|armv7a_hardfp|ppc64le|s390x|x86\n\t\tlatest|hardened|hardened-nomultilib|musl-hardened|musl-vanilla|nomultilib|systemd|uclibc-hardened|uclibc-vanilla')

# tags_to_arches = {
#    "latest": ["amd64","arm64","armv5tel","armv6j_hardfp","armv7a_hardfp","ppc64le","s390x","x86"]
#    ,"hardened": ["amd64","x86"]
#    ,"hardened-nomultilib": ["amd64"]
#    ,"musl-hardened": ["amd64"]
#    ,"musl-vanilla": ["amd64","x86"]
#    ,"nomultilib": ["amd64"]
#    ,"systemd": ["amd64","arm64","x86"]
#    ,"uclibc-hardened": ["amd64", "x86"]
#    ,"uclibc-vanilla": ["amd64","x86"]
#    }

# arches_to_tag = { v: k for k, v in tags_to_arches.items() }


dockerfile_path = 'include/dockerfiles/gentoomuch-stage3/'
lines = read_file_lines(os.path.join(dockerfile_path, 'step1.Dockerfile'))
if only_arch:
    for l in read_file_lines(os.path.join(dockerfile_path, 'step2.Dockerfile.archonly')):
        lines.append(l)
else:
    for l in read_file_lines(os.path.join(dockerfile_path, 'step2.Dockerfile.fully-loaded')):
        lines.append(l)
for l in read_file_lines(os.path.join(dockerfile_path, 'step3.Dockerfile')):
    lines.append(l)
if not os.path.isdir('work/gentoomuch-stage3'):
    os.mkdir('work/gentoomuch-stage3')


outfile = open('work/gentoomuch-stage3/Dockerfile', 'w')
outfile.writelines(lines)
outfile.close()

attempt_msg_prefix = '[GentooMuch.pull-stage3] Attempted to pull stage3 of arch "' 
tag_msg = '" wih tag, "' 
build_arg = ' --build-arg '
sys_cmd_head = 'docker image rm localhost:5000/gentoomuch-stage3:latest & docker image rm gentoomuch-bootstrap & cd work/gentoomuch-stage3 && docker build '
sys_cmd_tail = ' -t gentoomuch-bootstrap .'

common_args = build_arg + 'ARCH=' + arch + build_arg + 'MICROARCH=' + arch

if not only_arch:
    common_args = common_args + build_arg + 'SUFFIX=' + tag + ' '
    #print(attempt_msg_prefix + arch + tag_msg + tag + '" from gentoo\'s upstream')
if custom_http:
    http_msg = '" from custom http-server "'
    common_args = common_args + build_arg + 'DIST=' + http
code = os.system(sys_cmd_head + common_args + sys_cmd_tail)
    #print(attempt_msg_prefix + arch +  tag_msg + tag + http_msg + http +  '"')
if code !=0:
    sys.exit('GentooMuch.pull-stage3 First assembled Dockerfile failed pulling')
code = os.system('cp include/dockerfiles/gentoomuch-stage3/step4.Dockerfile work/gentoomuch-stage3/Dockerfile && cd work/gentoomuch-stage3 && docker build -t localhost:5000/gentoomuch-stage3:latest .')
if code != 0:
    sys.exit('[GentooMuch.pull-stage3] Application ended with error code ' + str(code))

