#!/usr/bin/env python3

import os, sys





#code = os.system('cp -R include/docker/zentoo-stage3 work && cd work/zentoo-stage3 && docker build -t localhost:5000/zentoo-stage3:latest .')
#if code != 0:
#    sys.exit(code)

code = os.system('cp -R include/docker/zentoo-rsync work && cd work/zentoo-rsync && docker build -t localhost:5000/zentoo-rsync:latest .')
if code != 0:
    sys.exit(code)

code = os.system('cp -R include/docker/zentoo-caddy work && cd work/zentoo-caddy && docker build -t localhost:5000/zentoo-caddy:latest .')
if code != 0:
    sys.exit(code)
