#!/usr/bin/env python3
# This is a frontend to the portage_directory_combiner, allowing user to manually switch to one of the stage defines when needed.
import os, sys
from include.gentoomuch_common import  config_path, read_file_lines, write_file_lines, current_portage_path
from include.portage_directory_combiner import portage_directory_combiner
usage_msg = "Usage: switch-config <config-name>"
if len(sys.argv) < 2 or len(sys.argv) > 3:
    sys.exit(usage_msg)
else:
    current_stage = sys.argv[1]
combiner = portage_directory_combiner()
combiner.process_stage_defines(current_stage)
if os.path.isdir(config_path):
    open(current_portage_path, 'w').write(current_stage)
