#!/usr/bin/env python3

# This is a frontend to the portage_directory_combiner

import os, sys
from include.gentoomuch_common import read_file_lines, write_file_lines

combiner = portage_directory_combiner()


