#!/bin/sh
cd config/portage/repos.conf && cd ../../.. && docker-compose down && docker-compose up -d && docker-compose run zentoo-builder bash -c 'emerge --sync' && cd config/portage/repos.conf && cd ../../..
